DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
CONTIKI_PROJECT = hello-world

all: $(CONTIKI_PROJECT)

CONTIKI_WITH_IPV6 = 1
CONTIKI_WITH_RIME = 1

#V=1

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
